### ISSUE TITLE
Video generation with custom image pairs

### ISSUE THREAD

**Issue by chaudatascience** [oooolga/Ctrl-V#2]
Hi,

I have a set of image pairs consisting of the first and last frames, each with bounding boxes. 
How can I utilize code to create videos for custom images? 

Is there any quick way to test it out?
Any guidance would be appreciated!

Best, 
Chau

**Comment by oooolga** [comment]
Hi @chaudatascience,

We trained our model exclusively on autonomous driving datasets. If your image pairs consist of street-view images from a first-person view camera (dash camera images), I can upload our trained weights to HG for you to test.

If the images are not related to cars, we do not have a pre-trained weight for such tasks at the moment. However, you can utilize our code to train a model for that purpose. We may train our model on other types of data and upload the weights in the future.

Cheers,
Olga

**Comment by chaudatascience** [comment]
Got it, thank you!
